import 'package:flutter/material.dart';

// String Map
Map<String, TextStyle> codeStringMap = {
  "if": const TextStyle(color: Colors.red),
  "else": const TextStyle(color: Colors.red),
  "String": const TextStyle(color: Colors.green),
  "int": const TextStyle(color: Colors.green),
  "class": const TextStyle(color: Colors.red),
  "extends": const TextStyle(color: Colors.red),
  "override": const TextStyle(color: Colors.blue),
  "Widget": const TextStyle(color: Colors.green),
  "BuildContext": const TextStyle(color: Colors.orange),
  "return": const TextStyle(color: Colors.red),
  "Scaffold": const TextStyle(color: Colors.green),
  "body": const TextStyle(color: Colors.orange),
  "FutureBuilder": const TextStyle(color: Colors.green),
  "future": const TextStyle(color: Colors.orange),
  "builder": const TextStyle(color: Colors.orange),
  "document": const TextStyle(color: Colors.blue),
  "get": const TextStyle(color: Colors.green),
  "AsyncSnapshot": const TextStyle(color: Colors.red),
  "snapshot": const TextStyle(color: Colors.orange),
  "context": const TextStyle(color: Colors.orange),
  "done": const TextStyle(color: Colors.blue),
  "none": const TextStyle(color: Colors.blue),
  "hasData": const TextStyle(color: Colors.blue),
  "print": const TextStyle(color: Colors.green),
  "Padding": const TextStyle(color: Colors.green),
  "padding": const TextStyle(color: Colors.orange),
  "const": const TextStyle(color: Colors.red),
  "top": const TextStyle(color: Colors.orange),
  "left": const TextStyle(color: Colors.orange),
  "right": const TextStyle(color: Colors.orange),
  "bottom": const TextStyle(color: Colors.orange),

  "child": const TextStyle(color: Colors.orange),
  "Column": const TextStyle(color: Colors.green),
  "children": const TextStyle(color: Colors.orange),
  "Text": const TextStyle(color: Colors.green),
  "List": const TextStyle(color: Colors.green),
  "void": const TextStyle(color: Colors.red),
  "singleWhere": const TextStyle(color: Colors.blue),
  "item": const TextStyle(color: Colors.orange),
  "import": const TextStyle(color: Colors.red),
  "main": const TextStyle(color: Colors.green),
  "runApp": const TextStyle(color: Colors.red),
  "App": const TextStyle(color: Colors.green),
  "StatelessWidget": const TextStyle(color: Colors.green),
  "StatefulWidget": const TextStyle(color: Colors.green),
  "package:cloud_firestore/cloud_firestore.dart":
      const TextStyle(color: Colors.orange),
  "material": const TextStyle(color: Colors.orange),
  "flutter": const TextStyle(color: Colors.orange),
  "package": const TextStyle(color: Colors.orange),
  "firebase_core": const TextStyle(color: Colors.orange),
  "dart": const TextStyle(color: Colors.orange),
  "Firebase": const TextStyle(color: Colors.green),
  "FirebaseFirestore": const TextStyle(color: Colors.green),
  "instance": const TextStyle(color: Colors.blue),
  "initializeApp": const TextStyle(color: Colors.blue),
  "collection": const TextStyle(color: Colors.blue),
  "doc": const TextStyle(color: Colors.blue),
  "MyAwesomeApp": const TextStyle(color: Colors.green),
  "SomethingWentWrong": const TextStyle(color: Colors.green),
  "Loading": const TextStyle(color: Colors.green),
  "MaterialApp": const TextStyle(color: Colors.green),
  "debugShowCheckedModeBanner": const TextStyle(color: Colors.orange),
  "theme": const TextStyle(color: Colors.orange),
  "ThemeData": const TextStyle(color: Colors.green),
  "true": const TextStyle(color: Colors.blue),
  "false": const TextStyle(color: Colors.blue),
  "primarySwatch": const TextStyle(color: Colors.orange),
  "Colors": const TextStyle(color: Colors.green),
  "home": const TextStyle(color: Colors.orange),
  "FirstRoute": const TextStyle(color: Colors.green),
  "title": const TextStyle(color: Colors.orange),
  "final": const TextStyle(color: Colors.red),
  "createState": const TextStyle(color: Colors.green),
  "initState": const TextStyle(color: Colors.green),
  "super": const TextStyle(color: Colors.red),
  "Container": const TextStyle(color: Colors.green),
  "height": const TextStyle(color: Colors.orange),
  "overflow": const TextStyle(color: Colors.orange),
  "style": const TextStyle(color: Colors.orange),
  "TextStyle": const TextStyle(color: Colors.green),
  "fontSize": const TextStyle(color: Colors.orange),
  "CircularProgressIndicator": const TextStyle(color: Colors.green),
  "Future": const TextStyle(color: Colors.green),
  "DocumentSnapshot": const TextStyle(color: Colors.green),
  "getData": const TextStyle(color: Colors.green),
  "async": const TextStyle(color: Colors.red),
  "await": const TextStyle(color: Colors.red),
  "buildscript": const TextStyle(color: Colors.blue),
  "repositories": const TextStyle(color: Colors.blue),
  "dependencies": const TextStyle(color: Colors.blue),
  "maven": const TextStyle(color: Colors.green),
  "url": const TextStyle(color: Colors.green),
  "jcenter": const TextStyle(color: Colors.green),
  "classpath": const TextStyle(color: Colors.green),
  "https://dl.google.com/dl/android/maven2":
      const TextStyle(color: Colors.orange),
  "com.android.tools.build:gradle:3.1.2": const TextStyle(color: Colors.orange),
  "com.google.gms:google-services:4.3.8": const TextStyle(color: Colors.orange),
  "Command": const TextStyle(color: Colors.grey, fontStyle: FontStyle.italic),
  "Not": const TextStyle(color: Colors.grey, fontStyle: FontStyle.italic),
  "Worked": const TextStyle(color: Colors.grey, fontStyle: FontStyle.italic),
  "To": const TextStyle(color: Colors.grey, fontStyle: FontStyle.italic),
  "cd": const TextStyle(color: Colors.orange),
  "Program Files Folder or any another folder that contains the '.git' hidden folder":
      const TextStyle(color: Colors.grey, fontStyle: FontStyle.italic),

  // Hints
  "CODE": const TextStyle(color: Colors.grey, fontStyle: FontStyle.italic),
  "2 in range instead of 3 for example":
      const TextStyle(color: Colors.grey, fontStyle: FontStyle.italic),
  "use String data type instead of int for example":
      const TextStyle(color: Colors.grey, fontStyle: FontStyle.italic),
  "Missing required positional argument":
      const TextStyle(color: Colors.grey, fontStyle: FontStyle.italic),
  "set a default value":
      const TextStyle(color: Colors.grey, fontStyle: FontStyle.italic),
  "mounted": const TextStyle(color: Colors.green, fontStyle: FontStyle.italic),
  "Solution": const TextStyle(color: Colors.grey, fontStyle: FontStyle.italic),
  "Point": const TextStyle(color: Colors.grey, fontStyle: FontStyle.italic),
  "Error": const TextStyle(color: Colors.grey, fontStyle: FontStyle.italic),
  "Correct": const TextStyle(color: Colors.grey, fontStyle: FontStyle.italic),
  "Code": const TextStyle(color: Colors.grey, fontStyle: FontStyle.italic),
  "Issue Point":
      const TextStyle(color: Colors.grey, fontStyle: FontStyle.italic),
  "First Example":
      const TextStyle(color: Colors.grey, fontStyle: FontStyle.italic),
  "Second Example":
      const TextStyle(color: Colors.grey, fontStyle: FontStyle.italic),
  "Initialize FlutterFire":
      const TextStyle(color: Colors.grey, fontStyle: FontStyle.italic),
  "Check for errors":
      const TextStyle(color: Colors.grey, fontStyle: FontStyle.italic),
  "Once complete, show your application":
      const TextStyle(color: Colors.grey, fontStyle: FontStyle.italic),
  "Otherwise, show something whilst waiting for initialization to complete":
      const TextStyle(color: Colors.grey, fontStyle: FontStyle.italic),
};

// Pattern Map
Map<String, TextStyle> codePatternMap = {
  r'\:': const TextStyle(color: Colors.orange),
  r'\>': const TextStyle(color: Colors.red),
  r'\<': const TextStyle(color: Colors.red),
  r"\]": const TextStyle(color: Colors.red),
  r"\[": const TextStyle(color: Colors.red),
  r"\?": const TextStyle(color: Colors.red),
  r"/": const TextStyle(color: Colors.grey),
  r"\=": const TextStyle(color: Colors.red),
  r"\)": const TextStyle(color: Colors.red),
  r"\(": const TextStyle(color: Colors.red),
  r"\{": const TextStyle(color: Colors.red),
  r"\}": const TextStyle(color: Colors.red),
  r"[0123456789]": const TextStyle(color: Colors.blue),
  r"\$": const TextStyle(color: Colors.blue),
  r"\@": const TextStyle(color: Colors.blue),
  r"\.": const TextStyle(color: Colors.orange),
};
