// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCencpxhbkMaKCNzzAtsjoAksqQigg3Lc8',
    appId: '1:169030454232:web:b14c78ffb1532872fe80ad',
    messagingSenderId: '169030454232',
    projectId: 'amgflutter-1c52c',
    authDomain: 'amgflutter-1c52c.firebaseapp.com',
    storageBucket: 'amgflutter-1c52c.appspot.com',
    measurementId: 'G-4MKQBGQ9B4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2Gys2wazDzmwWsjdPEMt0pm_No3HuuIg',
    appId: '1:169030454232:android:e90ee126c7eab407fe80ad',
    messagingSenderId: '169030454232',
    projectId: 'amgflutter-1c52c',
    storageBucket: 'amgflutter-1c52c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCc_9GpFZGG-GKl9YmN2VnkL6NaWRnTaGc',
    appId: '1:169030454232:ios:246113e82a93dbbafe80ad',
    messagingSenderId: '169030454232',
    projectId: 'amgflutter-1c52c',
    storageBucket: 'amgflutter-1c52c.appspot.com',
    iosBundleId: 'com.example.amgFlutterGuide',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCc_9GpFZGG-GKl9YmN2VnkL6NaWRnTaGc',
    appId: '1:169030454232:ios:246113e82a93dbbafe80ad',
    messagingSenderId: '169030454232',
    projectId: 'amgflutter-1c52c',
    storageBucket: 'amgflutter-1c52c.appspot.com',
    iosBundleId: 'com.example.amgFlutterGuide',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCencpxhbkMaKCNzzAtsjoAksqQigg3Lc8',
    appId: '1:169030454232:web:20ef3033d796eb8bfe80ad',
    messagingSenderId: '169030454232',
    projectId: 'amgflutter-1c52c',
    authDomain: 'amgflutter-1c52c.firebaseapp.com',
    storageBucket: 'amgflutter-1c52c.appspot.com',
    measurementId: 'G-CSRTD0JEGJ',
  );
}
